# Generated by Django 3.1.5 on 2021-01-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210110_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='identifier',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
